export HTTP_STATUS_BAD_GATEWAY,
    HTTP_STATUS_BAD_REQUEST,
    HTTP_STATUS_CONFLICT,
    HTTP_STATUS_CONTINUE,
    HTTP_STATUS_EXPECTATION_FAILED,
    HTTP_STATUS_FORBIDDEN,
    HTTP_STATUS_FOUND,
    HTTP_STATUS_GATEWAY_TIMEOUT,
    HTTP_STATUS_GONE,
    HTTP_STATUS_HTTP_VERSION_NOT_SUPPORTED,
    HTTP_STATUS_INTERNAL_SERVER_ERROR,
    HTTP_STATUS_LENGTH_REQUIRED,
    HTTP_STATUS_METHOD_NOT_ALLOWED,
    HTTP_STATUS_MOVED_PERMANENTLY,
    HTTP_STATUS_NOT_ACCEPTABLE,
    HTTP_STATUS_NOT_FOUND,
    HTTP_STATUS_NOT_IMPLEMENTED,
    HTTP_STATUS_NOT_MODIFIED,
    HTTP_STATUS_NO_CONTENT,
    HTTP_STATUS_OK,
    HTTP_STATUS_PARTIAL_CONTENT,
    HTTP_STATUS_PAYMENT_REQUIRED,
    HTTP_STATUS_PRECONDITION_FAILED,
    HTTP_STATUS_PROXY_AUTH_REQUIRED,
    HTTP_STATUS_REQUEST_TIMEOUT,
    HTTP_STATUS_REQ_ENTITY_TOO_LARGE,
    HTTP_STATUS_REQ_RANGE_NOT_SATISFIABLE,
    HTTP_STATUS_REQ_URI_TOO_LONG,
    HTTP_STATUS_SEE_OTHER,
    HTTP_STATUS_SERVICE_UNAVAILABLE,
    HTTP_STATUS_UNAUTHORIZED,
    HTTP_STATUS_UNSUPPORTED_MEDIA_TYPE

const HTTP_STATUS_CONTINUE = 100 % UInt32
const HTTP_STATUS_OK = 200 % UInt32
const HTTP_STATUS_NO_CONTENT = 204 % UInt32
const HTTP_STATUS_PARTIAL_CONTENT = 206 % UInt32
const HTTP_STATUS_MOVED_PERMANENTLY = 301 % UInt32
const HTTP_STATUS_FOUND = 302 % UInt32
const HTTP_STATUS_SEE_OTHER = 303 % UInt32
const HTTP_STATUS_NOT_MODIFIED = 304 % UInt32
const HTTP_STATUS_BAD_REQUEST = 400 % UInt32
const HTTP_STATUS_UNAUTHORIZED = 401 % UInt32
const HTTP_STATUS_PAYMENT_REQUIRED = 402 % UInt32
const HTTP_STATUS_FORBIDDEN = 403 % UInt32
const HTTP_STATUS_NOT_FOUND = 404 % UInt32
const HTTP_STATUS_METHOD_NOT_ALLOWED = 405 % UInt32
const HTTP_STATUS_NOT_ACCEPTABLE = 406 % UInt32
const HTTP_STATUS_PROXY_AUTH_REQUIRED = 407 % UInt32
const HTTP_STATUS_REQUEST_TIMEOUT = 408 % UInt32
const HTTP_STATUS_CONFLICT = 409 % UInt32
const HTTP_STATUS_GONE = 410 % UInt32
const HTTP_STATUS_LENGTH_REQUIRED = 411 % UInt32
const HTTP_STATUS_PRECONDITION_FAILED = 412 % UInt32
const HTTP_STATUS_REQ_ENTITY_TOO_LARGE = 413 % UInt32
const HTTP_STATUS_REQ_URI_TOO_LONG = 414 % UInt32
const HTTP_STATUS_UNSUPPORTED_MEDIA_TYPE = 415 % UInt32
const HTTP_STATUS_REQ_RANGE_NOT_SATISFIABLE = 416 % UInt32
const HTTP_STATUS_EXPECTATION_FAILED = 417 % UInt32
const HTTP_STATUS_INTERNAL_SERVER_ERROR = 500 % UInt32
const HTTP_STATUS_NOT_IMPLEMENTED = 501 % UInt32
const HTTP_STATUS_BAD_GATEWAY = 502 % UInt32
const HTTP_STATUS_SERVICE_UNAVAILABLE = 503 % UInt32
const HTTP_STATUS_GATEWAY_TIMEOUT = 504 % UInt32
const HTTP_STATUS_HTTP_VERSION_NOT_SUPPORTED = 505 % UInt32