export CONTEXT_PORT_NO_LISTEN,
    CONTEXT_PORT_NO_LISTEN_SERVER

export EXTARG_DEC,
    EXTARG_NONE,
    EXTARG_OPT_DEC

export H2SET_COUNT,
    H2SET_ENABLE_CONNECT_PROTOCOL,
    H2SET_ENABLE_PUSH,
    H2SET_HEADER_TABLE_SIZE,
    H2SET_INITIAL_WINDOW_SIZE,
    H2SET_MAX_CONCURRENT_STREAMS,
    H2SET_MAX_FRAME_SIZE,
    H2SET_MAX_HEADER_LIST_SIZE,
    H2SET_RESERVED7

export LCCSCF_ACCEPT_TLS_DOWNGRADE_REDIRECTS,
    LCCSCF_ALLOW_EXPIRED,
    LCCSCF_ALLOW_INSECURE,
    LCCSCF_ALLOW_SELFSIGNED,
    LCCSCF_CACHE_COOKIES,
    LCCSCF_CONMON,
    LCCSCF_H2_AUTH_BEARER,
    LCCSCF_H2_HEXIFY_AUTH_TOKEN,
    LCCSCF_H2_MANUAL_RXFLOW,
    LCCSCF_H2_PRIOR_KNOWLEDGE,
    LCCSCF_H2_QUIRK_NGHTTP2_END_STREAM,
    LCCSCF_H2_QUIRK_OVERFLOWS_TXCR,
    LCCSCF_HTTP_MULTIPART_MIME,
    LCCSCF_HTTP_NO_FOLLOW_REDIRECT,
    LCCSCF_HTTP_X_WWW_FORM_URLENCODED,
    LCCSCF_IP_HIGH_RELIABILITY,
    LCCSCF_IP_HIGH_THROUGHPUT,
    LCCSCF_IP_LOW_COST,
    LCCSCF_IP_LOW_LATENCY,
    LCCSCF_MUXABLE_STREAM,
    LCCSCF_PIPELINE,
    LCCSCF_PRIORITIZE_READS,
    LCCSCF_SECSTREAM_CLIENT,
    LCCSCF_SECSTREAM_PROXY_LINK,
    LCCSCF_SECSTREAM_PROXY_ONWARD,
    LCCSCF_SKIP_SERVER_CERT_HOSTNAME_CHECK,
    LCCSCF_USE_SSL,
    LCCSCF_WAKE_SUSPEND__VALIDITY
    
export LLLF_LOG_CONTEXT_AWARE,
    LLLF_LOG_TIMESTAMP,
    LLLF_SECRECY_BEARER,
    LLLF_SECRECY_PII,
    LLL_CLIENT,
    LLL_COUNT,
    LLL_DEBUG,
    LLL_ERR,
    LLL_EXT,
    LLL_HEADER,
    LLL_INFO,
    LLL_LATENCY,
    LLL_NOTICE,
    LLL_PARSER,
    LLL_THREAD,
    LLL_USER,
    LLL_WARN
    
export LWSAHH_CODE_MASK,
    LWSAHH_FLAG_NO_SERVER_NAME,
    LWSAUTHM_BASIC_AUTH_CALLBACK,
    LWSAUTHM_DEFAULT,
    LWSHUMETH_COLON_PATH,
    LWSHUMETH_CONNECT,
    LWSHUMETH_DELETE,
    LWSHUMETH_GET,
    LWSHUMETH_HEAD,
    LWSHUMETH_OPTIONS,
    LWSHUMETH_PATCH,
    LWSHUMETH_POST,
    LWSHUMETH_PUT,
    LWSMPRO_CALLBACK,
    LWSMPRO_CGI,
    LWSMPRO_FILE,
    LWSMPRO_HTTP,
    LWSMPRO_HTTPS,
    LWSMPRO_REDIR_HTTP,
    LWSMPRO_REDIR_HTTPS,
    LWSTXCR_PEER_TO_US,
    LWSTXCR_US_TO_PEER
    
export WS_ZERO,
    RX_BUFF_SIZE,
    TX_PACKET_SIZE


const EXTARG_NONE = 0 % UInt32
const EXTARG_DEC = 1 % UInt32
const EXTARG_OPT_DEC = 2 % UInt32

const LWSMPRO_HTTP = 0 % UInt32
const LWSMPRO_HTTPS = 1 % UInt32
const LWSMPRO_FILE = 2 % UInt32
const LWSMPRO_CGI = 3 % UInt32
const LWSMPRO_REDIR_HTTP = 4 % UInt32
const LWSMPRO_REDIR_HTTPS = 5 % UInt32
const LWSMPRO_CALLBACK = 6 % UInt32

const LWSAUTHM_DEFAULT = 0 % UInt32
const LWSAUTHM_BASIC_AUTH_CALLBACK = 268435456 % UInt32

const LCCSCF_USE_SSL = 1 % UInt32
const LCCSCF_ALLOW_SELFSIGNED = 2 % UInt32
const LCCSCF_SKIP_SERVER_CERT_HOSTNAME_CHECK = 4 % UInt32
const LCCSCF_ALLOW_EXPIRED = 8 % UInt32
const LCCSCF_ALLOW_INSECURE = 16 % UInt32
const LCCSCF_H2_QUIRK_NGHTTP2_END_STREAM = 32 % UInt32
const LCCSCF_H2_QUIRK_OVERFLOWS_TXCR = 64 % UInt32
const LCCSCF_H2_AUTH_BEARER = 128 % UInt32
const LCCSCF_H2_HEXIFY_AUTH_TOKEN = 256 % UInt32
const LCCSCF_H2_MANUAL_RXFLOW = 512 % UInt32
const LCCSCF_HTTP_MULTIPART_MIME = 1024 % UInt32
const LCCSCF_HTTP_X_WWW_FORM_URLENCODED = 2048 % UInt32
const LCCSCF_HTTP_NO_FOLLOW_REDIRECT = 4096 % UInt32
const LCCSCF_PIPELINE = 65536 % UInt32
const LCCSCF_MUXABLE_STREAM = 131072 % UInt32
const LCCSCF_H2_PRIOR_KNOWLEDGE = 262144 % UInt32
const LCCSCF_WAKE_SUSPEND__VALIDITY = 524288 % UInt32
const LCCSCF_PRIORITIZE_READS = 1048576 % UInt32
const LCCSCF_SECSTREAM_CLIENT = 2097152 % UInt32
const LCCSCF_SECSTREAM_PROXY_LINK = 4194304 % UInt32
const LCCSCF_SECSTREAM_PROXY_ONWARD = 8388608 % UInt32
const LCCSCF_IP_LOW_LATENCY = 16777216 % UInt32
const LCCSCF_IP_HIGH_THROUGHPUT = 33554432 % UInt32
const LCCSCF_IP_HIGH_RELIABILITY = 67108864 % UInt32
const LCCSCF_IP_LOW_COST = 134217728 % UInt32
const LCCSCF_CONMON = 268435456 % UInt32
const LCCSCF_ACCEPT_TLS_DOWNGRADE_REDIRECTS = 536870912 % UInt32
const LCCSCF_CACHE_COOKIES = 1073741824 % UInt32

const H2SET_HEADER_TABLE_SIZE = 1 % UInt32
const H2SET_ENABLE_PUSH = 2 % UInt32
const H2SET_MAX_CONCURRENT_STREAMS = 3 % UInt32
const H2SET_INITIAL_WINDOW_SIZE = 4 % UInt32
const H2SET_MAX_FRAME_SIZE = 5 % UInt32
const H2SET_MAX_HEADER_LIST_SIZE = 6 % UInt32
const H2SET_RESERVED7 = 7 % UInt32
const H2SET_ENABLE_CONNECT_PROTOCOL = 8 % UInt32
const H2SET_COUNT = 9 % UInt32

const LWSHUMETH_GET = 0 % UInt32
const LWSHUMETH_POST = 1 % UInt32
const LWSHUMETH_OPTIONS = 2 % UInt32
const LWSHUMETH_PUT = 3 % UInt32
const LWSHUMETH_PATCH = 4 % UInt32
const LWSHUMETH_DELETE = 5 % UInt32
const LWSHUMETH_CONNECT = 6 % UInt32
const LWSHUMETH_HEAD = 7 % UInt32
const LWSHUMETH_COLON_PATH = 8 % UInt32

const CONTEXT_PORT_NO_LISTEN = -1
const CONTEXT_PORT_NO_LISTEN_SERVER = -2

const LLL_ERR = 1 << 0
const LLL_WARN = 1 << 1
const LLL_NOTICE = 1 << 2
const LLL_INFO = 1 << 3
const LLL_DEBUG = 1 << 4
const LLL_PARSER = 1 << 5
const LLL_HEADER = 1 << 6
const LLL_EXT = 1 << 7
const LLL_CLIENT = 1 << 8
const LLL_LATENCY = 1 << 9
const LLL_USER = 1 << 10
const LLL_THREAD = 1 << 11
const LLL_COUNT = 12
const LLLF_SECRECY_PII = 1 << 16
const LLLF_SECRECY_BEARER = 1 << 17
const LLLF_LOG_TIMESTAMP = 1 << 18
const LLLF_LOG_CONTEXT_AWARE = 1 << 30
const AUTH_MODE_MASK = 0xf0000000
const LWSAHH_CODE_MASK = 1 << 16 - 1
const LWSAHH_FLAG_NO_SERVER_NAME = 1 << 30
const LWSTXCR_US_TO_PEER = 0
const LWSTXCR_PEER_TO_US = 1
const WS_ZERO = Cint(0)
const RX_BUFF_SIZE = 2000
const TX_PACKET_SIZE = 2000