export LWS_CALLBACK_ADD_HEADERS,
    LWS_CALLBACK_ADD_POLL_FD,
    LWS_CALLBACK_CGI,
    LWS_CALLBACK_CGI_PROCESS_ATTACH,
    LWS_CALLBACK_CGI_STDIN_COMPLETED,
    LWS_CALLBACK_CGI_STDIN_DATA,
    LWS_CALLBACK_CGI_TERMINATED,
    LWS_CALLBACK_CHANGE_MODE_POLL_FD,
    LWS_CALLBACK_CHECK_ACCESS_RIGHTS,
    LWS_CALLBACK_CHILD_CLOSING,
    LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER,
    LWS_CALLBACK_CLIENT_CLOSED,
    LWS_CALLBACK_CLIENT_CONFIRM_EXTENSION_SUPPORTED,
    LWS_CALLBACK_CLIENT_CONNECTION_ERROR,
    LWS_CALLBACK_CLIENT_ESTABLISHED,
    LWS_CALLBACK_CLIENT_FILTER_PRE_ESTABLISH,
    LWS_CALLBACK_CLIENT_HTTP_BIND_PROTOCOL,
    LWS_CALLBACK_CLIENT_HTTP_DROP_PROTOCOL,
    LWS_CALLBACK_CLIENT_HTTP_REDIRECT,
    LWS_CALLBACK_CLIENT_HTTP_WRITEABLE,
    LWS_CALLBACK_CLIENT_RECEIVE,
    LWS_CALLBACK_CLIENT_RECEIVE_PONG,
    LWS_CALLBACK_CLIENT_WRITEABLE,
    LWS_CALLBACK_CLOSED,
    LWS_CALLBACK_CLOSED_CLIENT_HTTP,
    LWS_CALLBACK_CLOSED_HTTP,
    LWS_CALLBACK_COMPLETED_CLIENT_HTTP,
    LWS_CALLBACK_CONFIRM_EXTENSION_OKAY,
    LWS_CALLBACK_CONNECTING,
    LWS_CALLBACK_DEL_POLL_FD,
    LWS_CALLBACK_ESTABLISHED,
    LWS_CALLBACK_ESTABLISHED_CLIENT_HTTP,
    LWS_CALLBACK_EVENT_WAIT_CANCELLED,
    LWS_CALLBACK_FILTER_HTTP_CONNECTION,
    LWS_CALLBACK_FILTER_NETWORK_CONNECTION,
    LWS_CALLBACK_FILTER_PROTOCOL_CONNECTION,
    LWS_CALLBACK_GET_THREAD_ID,
    LWS_CALLBACK_GS_EVENT,
    LWS_CALLBACK_HTTP,
    LWS_CALLBACK_HTTP_BIND_PROTOCOL,
    LWS_CALLBACK_HTTP_BODY,
    LWS_CALLBACK_HTTP_BODY_COMPLETION,
    LWS_CALLBACK_HTTP_CONFIRM_UPGRADE,
    LWS_CALLBACK_HTTP_DROP_PROTOCOL,
    LWS_CALLBACK_HTTP_FILE_COMPLETION,
    LWS_CALLBACK_HTTP_PMO,
    LWS_CALLBACK_HTTP_WRITEABLE,
    LWS_CALLBACK_LOCK_POLL,
    LWS_CALLBACK_MQTT_ACK,
    LWS_CALLBACK_MQTT_CLIENT_CLOSED,
    LWS_CALLBACK_MQTT_CLIENT_ESTABLISHED,
    LWS_CALLBACK_MQTT_CLIENT_RX,
    LWS_CALLBACK_MQTT_CLIENT_WRITEABLE,
    LWS_CALLBACK_MQTT_DROP_PROTOCOL,
    LWS_CALLBACK_MQTT_IDLE,
    LWS_CALLBACK_MQTT_NEW_CLIENT_INSTANTIATED,
    LWS_CALLBACK_MQTT_RESEND,
    LWS_CALLBACK_MQTT_SHADOW_TIMEOUT,
    LWS_CALLBACK_MQTT_SUBSCRIBED,
    LWS_CALLBACK_MQTT_UNSUBSCRIBED,
    LWS_CALLBACK_MQTT_UNSUBSCRIBE_TIMEOUT,
    LWS_CALLBACK_OPENSSL_LOAD_EXTRA_CLIENT_VERIFY_CERTS,
    LWS_CALLBACK_OPENSSL_LOAD_EXTRA_SERVER_VERIFY_CERTS,
    LWS_CALLBACK_OPENSSL_PERFORM_CLIENT_CERT_VERIFICATION,
    LWS_CALLBACK_OPENSSL_PERFORM_SERVER_CERT_VERIFICATION,
    LWS_CALLBACK_PROCESS_HTML,
    LWS_CALLBACK_PROTOCOL_DESTROY,
    LWS_CALLBACK_PROTOCOL_INIT,
    LWS_CALLBACK_RAW_ADOPT,
    LWS_CALLBACK_RAW_ADOPT_FILE,
    LWS_CALLBACK_RAW_CLOSE,
    LWS_CALLBACK_RAW_CLOSE_FILE,
    LWS_CALLBACK_RAW_CONNECTED,
    LWS_CALLBACK_RAW_FILE_BIND_PROTOCOL,
    LWS_CALLBACK_RAW_FILE_DROP_PROTOCOL,
    LWS_CALLBACK_RAW_PROXY_CLI_ADOPT,
    LWS_CALLBACK_RAW_PROXY_CLI_BIND_PROTOCOL,
    LWS_CALLBACK_RAW_PROXY_CLI_CLOSE,
    LWS_CALLBACK_RAW_PROXY_CLI_DROP_PROTOCOL,
    LWS_CALLBACK_RAW_PROXY_CLI_RX,
    LWS_CALLBACK_RAW_PROXY_CLI_WRITEABLE,
    LWS_CALLBACK_RAW_PROXY_SRV_ADOPT,
    LWS_CALLBACK_RAW_PROXY_SRV_BIND_PROTOCOL,
    LWS_CALLBACK_RAW_PROXY_SRV_CLOSE,
    LWS_CALLBACK_RAW_PROXY_SRV_DROP_PROTOCOL,
    LWS_CALLBACK_RAW_PROXY_SRV_RX,
    LWS_CALLBACK_RAW_PROXY_SRV_WRITEABLE,
    LWS_CALLBACK_RAW_RX,
    LWS_CALLBACK_RAW_RX_FILE,
    LWS_CALLBACK_RAW_SKT_BIND_PROTOCOL,
    LWS_CALLBACK_RAW_SKT_DROP_PROTOCOL,
    LWS_CALLBACK_RAW_WRITEABLE,
    LWS_CALLBACK_RAW_WRITEABLE_FILE,
    LWS_CALLBACK_RECEIVE,
    LWS_CALLBACK_RECEIVE_CLIENT_HTTP,
    LWS_CALLBACK_RECEIVE_CLIENT_HTTP_READ,
    LWS_CALLBACK_RECEIVE_PONG,
    LWS_CALLBACK_SERVER_NEW_CLIENT_INSTANTIATED,
    LWS_CALLBACK_SERVER_WRITEABLE,
    LWS_CALLBACK_SESSION_INFO,
    LWS_CALLBACK_SSL_INFO,
    LWS_CALLBACK_TIMER,
    LWS_CALLBACK_UNLOCK_POLL,
    LWS_CALLBACK_USER,
    LWS_CALLBACK_VERIFY_BASIC_AUTHORIZATION,
    LWS_CALLBACK_VHOST_CERT_AGING,
    LWS_CALLBACK_VHOST_CERT_UPDATE,
    LWS_CALLBACK_WSI_CREATE,
    LWS_CALLBACK_WSI_DESTROY,
    LWS_CALLBACK_WSI_TX_CREDIT_GET,
    LWS_CALLBACK_WS_CLIENT_BIND_PROTOCOL,
    LWS_CALLBACK_WS_CLIENT_DROP_PROTOCOL,
    LWS_CALLBACK_WS_EXT_DEFAULTS,
    LWS_CALLBACK_WS_PEER_INITIATED_CLOSE,
    LWS_CALLBACK_WS_SERVER_BIND_PROTOCOL,
    LWS_CALLBACK_WS_SERVER_DROP_PROTOCOL,
    LWS_BUILD_HASH,
    LWS_CB_REASON_AUX_BF__CGI,
    LWS_CB_REASON_AUX_BF__CGI_CHUNK_END,
    LWS_CB_REASON_AUX_BF__CGI_HEADERS,
    LWS_CB_REASON_AUX_BF__PROXY,
    LWS_CB_REASON_AUX_BF__PROXY_HEADERS,
    LWS_CB_REASON_AUX_BF__PROXY_TRANS_END,
    LWS_CLOSE_STATUS_ABNORMAL_CLOSE,
    LWS_CLOSE_STATUS_CLIENT_TRANSACTION_DONE,
    LWS_CLOSE_STATUS_EXTENSION_REQUIRED,
    LWS_CLOSE_STATUS_GOINGAWAY,
    LWS_CLOSE_STATUS_INVALID_PAYLOAD,
    LWS_CLOSE_STATUS_MESSAGE_TOO_LARGE,
    LWS_CLOSE_STATUS_NORMAL,
    LWS_CLOSE_STATUS_NOSTATUS,
    LWS_CLOSE_STATUS_NOSTATUS_CONTEXT_DESTROY,
    LWS_CLOSE_STATUS_NO_STATUS,
    LWS_CLOSE_STATUS_POLICY_VIOLATION,
    LWS_CLOSE_STATUS_PROTOCOL_ERR,
    LWS_CLOSE_STATUS_RESERVED,
    LWS_CLOSE_STATUS_TLS_FAILURE,
    LWS_CLOSE_STATUS_UNACCEPTABLE_OPCODE,
    LWS_CLOSE_STATUS_UNEXPECTED_CONDITION,
    LWS_CUS_AUTH,
    LWS_CUS_CHALLENGE,
    LWS_CUS_CONFIRM,
    LWS_CUS_CREATE_KEYS,
    LWS_CUS_CREATE_REQ,
    LWS_CUS_FAILED,
    LWS_CUS_IDLE,
    LWS_CUS_ISSUE,
    LWS_CUS_REG,
    LWS_CUS_REQ,
    LWS_CUS_STARTING,
    LWS_CUS_SUCCESS,
    LWS_EXT_CB_CLIENT_CONSTRUCT,
    LWS_EXT_CB_CONSTRUCT,
    LWS_EXT_CB_DESTROY,
    LWS_EXT_CB_NAMED_OPTION_SET,
    LWS_EXT_CB_OPTION_CONFIRM,
    LWS_EXT_CB_OPTION_DEFAULT,
    LWS_EXT_CB_OPTION_SET,
    LWS_EXT_CB_PACKET_TX_PRESEND,
    LWS_EXT_CB_PAYLOAD_RX,
    LWS_EXT_CB_PAYLOAD_TX,
    LWS_GI,
    LWS_H2_STREAM_SID,
    LWS_ILLEGAL_HTTP_CONTENT_LEN,
    LWS_INSTALL_DATADIR,
    LWS_INSTALL_LIBDIR,
    LWS_INVALID_FILE,
    LWS_KI,
    LWS_LIBRARY_VERSION,
    LWS_LIBRARY_VERSION_MAJOR,
    LWS_LIBRARY_VERSION_MINOR,
    LWS_LIBRARY_VERSION_NUMBER,
    LWS_LIBRARY_VERSION_PATCH,
    LWS_LOGGING_BITFIELD_CLEAR,
    LWS_LOGGING_BITFIELD_SET,
    LWS_MAX_SMP,
    LWS_MI,
    LWS_MS_PER_SEC,
    LWS_NS_PER_US,
    LWS_OPENSSL_CLIENT_CERTS,
    LWS_PI,
    LWS_PLUGIN_API_MAGIC,
    LWS_POLLERR,
    LWS_POLLHUP,
    LWS_POLLHUP_ERR,
    LWS_POLLIN,
    LWS_POLLOUT,
    LWS_PRE,
    LWS_PROTOCOL_LIST_TERM,
    LWS_RECOMMENDED_MIN_HEADER_SPACE,
    LWS_SEND_BUFFER_POST_PADDING,
    LWS_SEND_BUFFER_PRE_PADDING,
    LWS_SERVER_OPTION_ADOPT_APPLY_LISTEN_ACCEPT_CONFIG,
    LWS_SERVER_OPTION_ALLOW_HTTP_ON_HTTPS_LISTENER,
    LWS_SERVER_OPTION_ALLOW_LISTEN_SHARE,
    LWS_SERVER_OPTION_ALLOW_NON_SSL_ON_SSL_PORT,
    LWS_SERVER_OPTION_CREATE_VHOST_SSL_CTX,
    LWS_SERVER_OPTION_DISABLE_IPV6,
    LWS_SERVER_OPTION_DISABLE_OS_CA_CERTS,
    LWS_SERVER_OPTION_DISABLE_TLS_SESSION_CACHE,
    LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT,
    LWS_SERVER_OPTION_EXPLICIT_VHOSTS,
    LWS_SERVER_OPTION_FAIL_UPON_UNABLE_TO_BIND,
    LWS_SERVER_OPTION_FALLBACK_TO_APPLY_LISTEN_ACCEPT_CONFIG,
    LWS_SERVER_OPTION_GLIB,
    LWS_SERVER_OPTION_H2_JUST_FIX_WINDOW_UPDATE_OVERFLOW,
    LWS_SERVER_OPTION_H2_PRIOR_KNOWLEDGE,
    LWS_SERVER_OPTION_HTTP_HEADERS_SECURITY_BEST_PRACTICES_ENFORCE,
    LWS_SERVER_OPTION_IGNORE_MISSING_CERT,
    LWS_SERVER_OPTION_IPV6_V6ONLY_MODIFY,
    LWS_SERVER_OPTION_IPV6_V6ONLY_VALUE,
    LWS_SERVER_OPTION_JUST_USE_RAW_ORIGIN,
    LWS_SERVER_OPTION_LIBEV,
    LWS_SERVER_OPTION_LIBEVENT,
    LWS_SERVER_OPTION_LIBUV,
    LWS_SERVER_OPTION_NO_LWS_SYSTEM_STATES,
    LWS_SERVER_OPTION_PEER_CERT_NOT_REQUIRED,
    LWS_SERVER_OPTION_REDIRECT_HTTP_TO_HTTPS,
    LWS_SERVER_OPTION_REQUIRE_VALID_OPENSSL_CLIENT_CERT,
    LWS_SERVER_OPTION_SDEVENT,
    LWS_SERVER_OPTION_SKIP_PROTOCOL_INIT,
    LWS_SERVER_OPTION_SKIP_SERVER_CANONICAL_NAME,
    LWS_SERVER_OPTION_SSL_ECDH,
    LWS_SERVER_OPTION_SS_PROXY,
    LWS_SERVER_OPTION_STS,
    LWS_SERVER_OPTION_ULOOP,
    LWS_SERVER_OPTION_UNIX_SOCK,
    LWS_SERVER_OPTION_UV_NO_SIGSEGV_SIGFPE_SPIN,
    LWS_SERVER_OPTION_VALIDATE_UTF8,
    LWS_SERVER_OPTION_VHOST_UPG_STRICT_HOST_CHECK,
    LWS_SERVER_OPTION_VH_H2_HALF_CLOSED_LONG_POLL,
    LWS_SESSION_TAG_LEN,
    LWS_SIZEOFPTR,
    LWS_SOCK_INVALID,
    LWS_TI,
    LWS_TLS_CERT_INFO_AUTHORITY_KEY_ID,
    LWS_TLS_CERT_INFO_AUTHORITY_KEY_ID_ISSUER,
    LWS_TLS_CERT_INFO_AUTHORITY_KEY_ID_SERIAL,
    LWS_TLS_CERT_INFO_COMMON_NAME,
    LWS_TLS_CERT_INFO_DER_RAW,
    LWS_TLS_CERT_INFO_ISSUER_NAME,
    LWS_TLS_CERT_INFO_OPAQUE_PUBLIC_KEY,
    LWS_TLS_CERT_INFO_SUBJECT_KEY_ID,
    LWS_TLS_CERT_INFO_USAGE,
    LWS_TLS_CERT_INFO_VALIDITY_FROM,
    LWS_TLS_CERT_INFO_VALIDITY_TO,
    LWS_TLS_CERT_INFO_VERIFIED,
    LWS_TLS_REQ_ELEMENT_COMMON_NAME,
    LWS_TLS_REQ_ELEMENT_COUNT,
    LWS_TLS_REQ_ELEMENT_COUNTRY,
    LWS_TLS_REQ_ELEMENT_EMAIL,
    LWS_TLS_REQ_ELEMENT_LOCALITY,
    LWS_TLS_REQ_ELEMENT_ORGANIZATION,
    LWS_TLS_REQ_ELEMENT_STATE,
    LWS_TLS_REQ_ELEMENT_SUBJECT_ALT_NAME,
    LWS_TLS_SET_AUTH_PATH,
    LWS_TLS_SET_CERT_PATH,
    LWS_TLS_SET_DIR_URL,
    LWS_TLS_SET_KEY_PATH,
    LWS_TLS_TOTAL_COUNT,
    LWS_UFS_CLOSE,
    LWS_UFS_CONTENT,
    LWS_UFS_FINAL_CONTENT,
    LWS_UFS_OPEN,
    LWS_US_PER_MS,
    LWS_US_PER_SEC,
    LWS_WRITE_BINARY,
    LWS_WRITE_BUFLIST,
    LWS_WRITE_CLIENT_IGNORE_XOR_MASK,
    LWS_WRITE_CONTINUATION,
    LWS_WRITE_H2_STREAM_END,
    LWS_WRITE_HTTP,
    LWS_WRITE_HTTP_FINAL,
    LWS_WRITE_HTTP_HEADERS,
    LWS_WRITE_HTTP_HEADERS_CONTINUATION,
    LWS_WRITE_NO_FIN,
    LWS_WRITE_PING,
    LWS_WRITE_PONG,
    LWS_WRITE_RAW,
    LWS_WRITE_TEXT,
    LWS_CONTEXT_NULL,

const LWS_WRITE_TEXT = 0 % UInt32
const LWS_WRITE_BINARY = 1 % UInt32
const LWS_WRITE_CONTINUATION = 2 % UInt32
const LWS_WRITE_HTTP = 3 % UInt32
const LWS_WRITE_PING = 5 % UInt32
const LWS_WRITE_PONG = 6 % UInt32
const LWS_WRITE_HTTP_FINAL = 7 % UInt32
const LWS_WRITE_HTTP_HEADERS = 8 % UInt32
const LWS_WRITE_HTTP_HEADERS_CONTINUATION = 9 % UInt32
const LWS_WRITE_BUFLIST = 32 % UInt32
const LWS_WRITE_NO_FIN = 64 % UInt32
const LWS_WRITE_H2_STREAM_END = 128 % UInt32
const LWS_WRITE_CLIENT_IGNORE_XOR_MASK = 128 % UInt32

const LWS_CLOSE_STATUS_NOSTATUS = 0 % UInt32
const LWS_CLOSE_STATUS_NORMAL = 1000 % UInt32
const LWS_CLOSE_STATUS_GOINGAWAY = 1001 % UInt32
const LWS_CLOSE_STATUS_PROTOCOL_ERR = 1002 % UInt32
const LWS_CLOSE_STATUS_UNACCEPTABLE_OPCODE = 1003 % UInt32
const LWS_CLOSE_STATUS_RESERVED = 1004 % UInt32
const LWS_CLOSE_STATUS_NO_STATUS = 1005 % UInt32
const LWS_CLOSE_STATUS_ABNORMAL_CLOSE = 1006 % UInt32
const LWS_CLOSE_STATUS_INVALID_PAYLOAD = 1007 % UInt32
const LWS_CLOSE_STATUS_POLICY_VIOLATION = 1008 % UInt32
const LWS_CLOSE_STATUS_MESSAGE_TOO_LARGE = 1009 % UInt32
const LWS_CLOSE_STATUS_EXTENSION_REQUIRED = 1010 % UInt32
const LWS_CLOSE_STATUS_UNEXPECTED_CONDITION = 1011 % UInt32
const LWS_CLOSE_STATUS_TLS_FAILURE = 1015 % UInt32
const LWS_CLOSE_STATUS_CLIENT_TRANSACTION_DONE = 2000 % UInt32
const LWS_CLOSE_STATUS_NOSTATUS_CONTEXT_DESTROY = 9999 % UInt32

const LWS_CUS_IDLE = 0 % UInt32
const LWS_CUS_STARTING = 1 % UInt32
const LWS_CUS_SUCCESS = 2 % UInt32
const LWS_CUS_FAILED = 3 % UInt32
const LWS_CUS_CREATE_KEYS = 4 % UInt32
const LWS_CUS_REG = 5 % UInt32
const LWS_CUS_AUTH = 6 % UInt32
const LWS_CUS_CHALLENGE = 7 % UInt32
const LWS_CUS_CREATE_REQ = 8 % UInt32
const LWS_CUS_REQ = 9 % UInt32
const LWS_CUS_CONFIRM = 10 % UInt32
const LWS_CUS_ISSUE = 11 % UInt32

const LWS_TLS_REQ_ELEMENT_COUNTRY = 0 % UInt32
const LWS_TLS_REQ_ELEMENT_STATE = 1 % UInt32
const LWS_TLS_REQ_ELEMENT_LOCALITY = 2 % UInt32
const LWS_TLS_REQ_ELEMENT_ORGANIZATION = 3 % UInt32
const LWS_TLS_REQ_ELEMENT_COMMON_NAME = 4 % UInt32
const LWS_TLS_REQ_ELEMENT_SUBJECT_ALT_NAME = 5 % UInt32
const LWS_TLS_REQ_ELEMENT_EMAIL = 6 % UInt32
const LWS_TLS_REQ_ELEMENT_COUNT = 7 % UInt32
const LWS_TLS_SET_DIR_URL = 7 % UInt32
const LWS_TLS_SET_AUTH_PATH = 8 % UInt32
const LWS_TLS_SET_CERT_PATH = 9 % UInt32
const LWS_TLS_SET_KEY_PATH = 10 % UInt32
const LWS_TLS_TOTAL_COUNT = 11 % UInt32

const LWS_CALLBACK_PROTOCOL_INIT = 27 % UInt32
const LWS_CALLBACK_PROTOCOL_DESTROY = 28 % UInt32
const LWS_CALLBACK_WSI_CREATE = 29 % UInt32
const LWS_CALLBACK_WSI_DESTROY = 30 % UInt32
const LWS_CALLBACK_WSI_TX_CREDIT_GET = 103 % UInt32
const LWS_CALLBACK_OPENSSL_LOAD_EXTRA_CLIENT_VERIFY_CERTS = 21 % UInt32
const LWS_CALLBACK_OPENSSL_LOAD_EXTRA_SERVER_VERIFY_CERTS = 22 % UInt32
const LWS_CALLBACK_OPENSSL_PERFORM_CLIENT_CERT_VERIFICATION = 23 % UInt32
const LWS_CALLBACK_SSL_INFO = 67 % UInt32
const LWS_CALLBACK_OPENSSL_PERFORM_SERVER_CERT_VERIFICATION = 58 % UInt32
const LWS_CALLBACK_SERVER_NEW_CLIENT_INSTANTIATED = 19 % UInt32
const LWS_CALLBACK_HTTP = 12 % UInt32
const LWS_CALLBACK_HTTP_BODY = 13 % UInt32
const LWS_CALLBACK_HTTP_BODY_COMPLETION = 14 % UInt32
const LWS_CALLBACK_HTTP_FILE_COMPLETION = 15 % UInt32
const LWS_CALLBACK_HTTP_WRITEABLE = 16 % UInt32
const LWS_CALLBACK_CLOSED_HTTP = 5 % UInt32
const LWS_CALLBACK_FILTER_HTTP_CONNECTION = 18 % UInt32
const LWS_CALLBACK_ADD_HEADERS = 53 % UInt32
const LWS_CALLBACK_VERIFY_BASIC_AUTHORIZATION = 102 % UInt32
const LWS_CALLBACK_CHECK_ACCESS_RIGHTS = 51 % UInt32
const LWS_CALLBACK_PROCESS_HTML = 52 % UInt32
const LWS_CALLBACK_HTTP_BIND_PROTOCOL = 49 % UInt32
const LWS_CALLBACK_HTTP_DROP_PROTOCOL = 50 % UInt32
const LWS_CALLBACK_HTTP_CONFIRM_UPGRADE = 86 % UInt32
const LWS_CALLBACK_ESTABLISHED_CLIENT_HTTP = 44 % UInt32
const LWS_CALLBACK_CLOSED_CLIENT_HTTP = 45 % UInt32
const LWS_CALLBACK_RECEIVE_CLIENT_HTTP_READ = 48 % UInt32
const LWS_CALLBACK_RECEIVE_CLIENT_HTTP = 46 % UInt32
const LWS_CALLBACK_COMPLETED_CLIENT_HTTP = 47 % UInt32
const LWS_CALLBACK_CLIENT_HTTP_WRITEABLE = 57 % UInt32
const LWS_CALLBACK_CLIENT_HTTP_REDIRECT = 104 % UInt32
const LWS_CALLBACK_CLIENT_HTTP_BIND_PROTOCOL = 85 % UInt32
const LWS_CALLBACK_CLIENT_HTTP_DROP_PROTOCOL = 76 % UInt32
const LWS_CALLBACK_ESTABLISHED = 0 % UInt32
const LWS_CALLBACK_CLOSED = 4 % UInt32
const LWS_CALLBACK_SERVER_WRITEABLE = 11 % UInt32
const LWS_CALLBACK_RECEIVE = 6 % UInt32
const LWS_CALLBACK_RECEIVE_PONG = 7 % UInt32
const LWS_CALLBACK_WS_PEER_INITIATED_CLOSE = 38 % UInt32
const LWS_CALLBACK_FILTER_PROTOCOL_CONNECTION = 20 % UInt32
const LWS_CALLBACK_CONFIRM_EXTENSION_OKAY = 25 % UInt32
const LWS_CALLBACK_WS_SERVER_BIND_PROTOCOL = 77 % UInt32
const LWS_CALLBACK_WS_SERVER_DROP_PROTOCOL = 78 % UInt32
const LWS_CALLBACK_CLIENT_CONNECTION_ERROR = 1 % UInt32
const LWS_CALLBACK_CLIENT_FILTER_PRE_ESTABLISH = 2 % UInt32
const LWS_CALLBACK_CLIENT_ESTABLISHED = 3 % UInt32
const LWS_CALLBACK_CLIENT_CLOSED = 75 % UInt32
const LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER = 24 % UInt32
const LWS_CALLBACK_CLIENT_RECEIVE = 8 % UInt32
const LWS_CALLBACK_CLIENT_RECEIVE_PONG = 9 % UInt32
const LWS_CALLBACK_CLIENT_WRITEABLE = 10 % UInt32
const LWS_CALLBACK_CLIENT_CONFIRM_EXTENSION_SUPPORTED = 26 % UInt32
const LWS_CALLBACK_WS_EXT_DEFAULTS = 39 % UInt32
const LWS_CALLBACK_FILTER_NETWORK_CONNECTION = 17 % UInt32
const LWS_CALLBACK_WS_CLIENT_BIND_PROTOCOL = 79 % UInt32
const LWS_CALLBACK_WS_CLIENT_DROP_PROTOCOL = 80 % UInt32
const LWS_CALLBACK_GET_THREAD_ID = 31 % UInt32
const LWS_CALLBACK_ADD_POLL_FD = 32 % UInt32
const LWS_CALLBACK_DEL_POLL_FD = 33 % UInt32
const LWS_CALLBACK_CHANGE_MODE_POLL_FD = 34 % UInt32
const LWS_CALLBACK_LOCK_POLL = 35 % UInt32
const LWS_CALLBACK_UNLOCK_POLL = 36 % UInt32
const LWS_CALLBACK_CGI = 40 % UInt32
const LWS_CALLBACK_CGI_TERMINATED = 41 % UInt32
const LWS_CALLBACK_CGI_STDIN_DATA = 42 % UInt32
const LWS_CALLBACK_CGI_STDIN_COMPLETED = 43 % UInt32
const LWS_CALLBACK_CGI_PROCESS_ATTACH = 70 % UInt32
const LWS_CALLBACK_SESSION_INFO = 54 % UInt32
const LWS_CALLBACK_GS_EVENT = 55 % UInt32
const LWS_CALLBACK_HTTP_PMO = 56 % UInt32
const LWS_CALLBACK_RAW_PROXY_CLI_RX = 89 % UInt32
const LWS_CALLBACK_RAW_PROXY_SRV_RX = 90 % UInt32
const LWS_CALLBACK_RAW_PROXY_CLI_CLOSE = 91 % UInt32
const LWS_CALLBACK_RAW_PROXY_SRV_CLOSE = 92 % UInt32
const LWS_CALLBACK_RAW_PROXY_CLI_WRITEABLE = 93 % UInt32
const LWS_CALLBACK_RAW_PROXY_SRV_WRITEABLE = 94 % UInt32
const LWS_CALLBACK_RAW_PROXY_CLI_ADOPT = 95 % UInt32
const LWS_CALLBACK_RAW_PROXY_SRV_ADOPT = 96 % UInt32
const LWS_CALLBACK_RAW_PROXY_CLI_BIND_PROTOCOL = 97 % UInt32
const LWS_CALLBACK_RAW_PROXY_SRV_BIND_PROTOCOL = 98 % UInt32
const LWS_CALLBACK_RAW_PROXY_CLI_DROP_PROTOCOL = 99 % UInt32
const LWS_CALLBACK_RAW_PROXY_SRV_DROP_PROTOCOL = 100 % UInt32
const LWS_CALLBACK_RAW_RX = 59 % UInt32
const LWS_CALLBACK_RAW_CLOSE = 60 % UInt32
const LWS_CALLBACK_RAW_WRITEABLE = 61 % UInt32
const LWS_CALLBACK_RAW_ADOPT = 62 % UInt32
const LWS_CALLBACK_RAW_CONNECTED = 101 % UInt32
const LWS_CALLBACK_RAW_SKT_BIND_PROTOCOL = 81 % UInt32
const LWS_CALLBACK_RAW_SKT_DROP_PROTOCOL = 82 % UInt32
const LWS_CALLBACK_RAW_ADOPT_FILE = 63 % UInt32
const LWS_CALLBACK_RAW_RX_FILE = 64 % UInt32
const LWS_CALLBACK_RAW_WRITEABLE_FILE = 65 % UInt32
const LWS_CALLBACK_RAW_CLOSE_FILE = 66 % UInt32
const LWS_CALLBACK_RAW_FILE_BIND_PROTOCOL = 83 % UInt32
const LWS_CALLBACK_RAW_FILE_DROP_PROTOCOL = 84 % UInt32
const LWS_CALLBACK_TIMER = 73 % UInt32
const LWS_CALLBACK_EVENT_WAIT_CANCELLED = 71 % UInt32
const LWS_CALLBACK_CHILD_CLOSING = 69 % UInt32
const LWS_CALLBACK_CONNECTING = 105 % UInt32
const LWS_CALLBACK_VHOST_CERT_AGING = 72 % UInt32
const LWS_CALLBACK_VHOST_CERT_UPDATE = 74 % UInt32
const LWS_CALLBACK_MQTT_NEW_CLIENT_INSTANTIATED = 200 % UInt32
const LWS_CALLBACK_MQTT_IDLE = 201 % UInt32
const LWS_CALLBACK_MQTT_CLIENT_ESTABLISHED = 202 % UInt32
const LWS_CALLBACK_MQTT_SUBSCRIBED = 203 % UInt32
const LWS_CALLBACK_MQTT_CLIENT_WRITEABLE = 204 % UInt32
const LWS_CALLBACK_MQTT_CLIENT_RX = 205 % UInt32
const LWS_CALLBACK_MQTT_UNSUBSCRIBED = 206 % UInt32
const LWS_CALLBACK_MQTT_DROP_PROTOCOL = 207 % UInt32
const LWS_CALLBACK_MQTT_CLIENT_CLOSED = 208 % UInt32
const LWS_CALLBACK_MQTT_ACK = 209 % UInt32
const LWS_CALLBACK_MQTT_RESEND = 210 % UInt32
const LWS_CALLBACK_MQTT_UNSUBSCRIBE_TIMEOUT = 211 % UInt32
const LWS_CALLBACK_MQTT_SHADOW_TIMEOUT = 212 % UInt32
const LWS_CALLBACK_USER = 1000 % UInt32

const LWS_EXT_CB_CONSTRUCT = 4 % UInt32
const LWS_EXT_CB_CLIENT_CONSTRUCT = 5 % UInt32
const LWS_EXT_CB_DESTROY = 8 % UInt32
const LWS_EXT_CB_PACKET_TX_PRESEND = 12 % UInt32
const LWS_EXT_CB_PAYLOAD_TX = 21 % UInt32
const LWS_EXT_CB_PAYLOAD_RX = 22 % UInt32
const LWS_EXT_CB_OPTION_DEFAULT = 23 % UInt32
const LWS_EXT_CB_OPTION_SET = 24 % UInt32
const LWS_EXT_CB_OPTION_CONFIRM = 25 % UInt32
const LWS_EXT_CB_NAMED_OPTION_SET = 26 % UInt32

const LWS_UFS_CONTENT = 0 % UInt32
const LWS_UFS_FINAL_CONTENT = 1 % UInt32
const LWS_UFS_OPEN = 2 % UInt32
const LWS_UFS_CLOSE = 3 % UInt32

const LWS_TLS_CERT_INFO_VALIDITY_FROM = 0 % UInt32
const LWS_TLS_CERT_INFO_VALIDITY_TO = 1 % UInt32
const LWS_TLS_CERT_INFO_COMMON_NAME = 2 % UInt32
const LWS_TLS_CERT_INFO_ISSUER_NAME = 3 % UInt32
const LWS_TLS_CERT_INFO_USAGE = 4 % UInt32
const LWS_TLS_CERT_INFO_VERIFIED = 5 % UInt32
const LWS_TLS_CERT_INFO_OPAQUE_PUBLIC_KEY = 6 % UInt32
const LWS_TLS_CERT_INFO_DER_RAW = 7 % UInt32
const LWS_TLS_CERT_INFO_AUTHORITY_KEY_ID = 8 % UInt32
const LWS_TLS_CERT_INFO_AUTHORITY_KEY_ID_ISSUER = 9 % UInt32
const LWS_TLS_CERT_INFO_AUTHORITY_KEY_ID_SERIAL = 10 % UInt32
const LWS_TLS_CERT_INFO_SUBJECT_KEY_ID = 11 % UInt32

const LWS_INSTALL_DATADIR = "/workspace/destdir/share"
const LWS_INSTALL_LIBDIR = "/workspace/destdir/lib"
const LWS_LIBRARY_VERSION_MAJOR = 4
const LWS_LIBRARY_VERSION_MINOR = 3
const LWS_LIBRARY_VERSION_PATCH = 3
const LWS_LIBRARY_VERSION_NUMBER = LWS_LIBRARY_VERSION_MAJOR * 1000000 + LWS_LIBRARY_VERSION_MINOR * 1000 + LWS_LIBRARY_VERSION_PATCH
const LWS_MAX_SMP = 1
const LWS_BUILD_HASH = "v4.4.0"
const LWS_LIBRARY_VERSION = "4.4.0-v4.4.0"
const LWS_LOGGING_BITFIELD_CLEAR = 0
const LWS_LOGGING_BITFIELD_SET = 0
const LWS_OPENSSL_CLIENT_CERTS = "../share"
const LWS_US_PER_SEC = Int64(1000000)
const LWS_MS_PER_SEC = Int64(1000)
const LWS_US_PER_MS = Int64(1000)
const LWS_NS_PER_US = Int64(1000)
const LWS_KI = 1024
const LWS_MI = LWS_KI * 1024
const LWS_GI = LWS_MI * 1024

const LWS_POLLHUP = 0x0010
const LWS_POLLIN = 0x0001
const LWS_POLLOUT = 0x0004
const LWS_POLLERR = 0x0008
const LWS_POLLHUP_ERR = LWS_POLLHUP | LWS_POLLERR

const LWS_PROTOCOL_LIST_TERM = (C_NULL, C_NULL, 0, 0, 0, C_NULL, 0)
const LWS_ILLEGAL_HTTP_CONTENT_LEN = Culonglong(0xFFFFFFFFFFFFFFFF)
const LWS_SIZEOFPTR = Int(Sys.WORD_SIZE ÷ 8)

const _LWS_PAD_SIZE = Sys.WORD_SIZE == 64 && Sys.ARCH == :x86_64 ? 16 : Sys.WORD_SIZE ÷ 8

function _LWS_PAD(n::Int)
    mod_n = n % _LWS_PAD_SIZE
    return mod_n == 0 ? n : n + (_LWS_PAD_SIZE - mod_n)
end

const LWS_PRE = _LWS_PAD(4 + 10 + 2)
const LWS_TI = UInt64(LWS_GI) * 1024
const LWS_PI = UInt64(LWS_TI) * 1024

const LWS_INVALID_FILE = -1
const LWS_SOCK_INVALID = -1

const LWS_CB_REASON_AUX_BF__CGI = 1
const LWS_CB_REASON_AUX_BF__PROXY = 2
const LWS_CB_REASON_AUX_BF__CGI_CHUNK_END = 4
const LWS_CB_REASON_AUX_BF__CGI_HEADERS = 8
const LWS_CB_REASON_AUX_BF__PROXY_TRANS_END = 16
const LWS_CB_REASON_AUX_BF__PROXY_HEADERS = 32

const LWS_PLUGIN_API_MAGIC = 191

const LWS_SERVER_OPTION_REQUIRE_VALID_OPENSSL_CLIENT_CERT = Clonglong(1) << 1 | Clonglong(1) << 12
const LWS_SERVER_OPTION_SKIP_SERVER_CANONICAL_NAME = Clonglong(1) << 2
const LWS_SERVER_OPTION_ALLOW_NON_SSL_ON_SSL_PORT = Clonglong(1) << 3 | Clonglong(1) << 12
const LWS_SERVER_OPTION_LIBEV = Clonglong(1) << 4
const LWS_SERVER_OPTION_DISABLE_IPV6 = Clonglong(1) << 5
const LWS_SERVER_OPTION_DISABLE_OS_CA_CERTS = Clonglong(1) << 6
const LWS_SERVER_OPTION_PEER_CERT_NOT_REQUIRED = Clonglong(1) << 7
const LWS_SERVER_OPTION_VALIDATE_UTF8 = Clonglong(1) << 8
const LWS_SERVER_OPTION_SSL_ECDH = Clonglong(1) << 9 | Clonglong(1) << 12
const LWS_SERVER_OPTION_LIBUV = Clonglong(1) << 10
const LWS_SERVER_OPTION_REDIRECT_HTTP_TO_HTTPS = Clonglong(1) << 11 | Clonglong(1) << 12
const LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT = Clonglong(1) << 12
const LWS_SERVER_OPTION_EXPLICIT_VHOSTS = Clonglong(1) << 13
const LWS_SERVER_OPTION_UNIX_SOCK = Clonglong(1) << 14
const LWS_SERVER_OPTION_STS = Clonglong(1) << 15
const LWS_SERVER_OPTION_IPV6_V6ONLY_MODIFY = Clonglong(1) << 16
const LWS_SERVER_OPTION_IPV6_V6ONLY_VALUE = Clonglong(1) << 17
const LWS_SERVER_OPTION_UV_NO_SIGSEGV_SIGFPE_SPIN = Clonglong(1) << 18
const LWS_SERVER_OPTION_JUST_USE_RAW_ORIGIN = Clonglong(1) << 19
const LWS_SERVER_OPTION_FALLBACK_TO_APPLY_LISTEN_ACCEPT_CONFIG = Clonglong(1) << 20
const LWS_SERVER_OPTION_LIBEVENT = Clonglong(1) << 21
const LWS_SERVER_OPTION_ADOPT_APPLY_LISTEN_ACCEPT_CONFIG = Clonglong(1) << 22
const LWS_SERVER_OPTION_ALLOW_LISTEN_SHARE = Clonglong(1) << 23
const LWS_SERVER_OPTION_CREATE_VHOST_SSL_CTX = Clonglong(1) << 24
const LWS_SERVER_OPTION_SKIP_PROTOCOL_INIT = Clonglong(1) << 25
const LWS_SERVER_OPTION_IGNORE_MISSING_CERT = Clonglong(1) << 26
const LWS_SERVER_OPTION_VHOST_UPG_STRICT_HOST_CHECK = Clonglong(1) << 27
const LWS_SERVER_OPTION_HTTP_HEADERS_SECURITY_BEST_PRACTICES_ENFORCE = Clonglong(1) << 28
const LWS_SERVER_OPTION_ALLOW_HTTP_ON_HTTPS_LISTENER = Clonglong(1) << 29
const LWS_SERVER_OPTION_FAIL_UPON_UNABLE_TO_BIND = Clonglong(1) << 30
const LWS_SERVER_OPTION_H2_JUST_FIX_WINDOW_UPDATE_OVERFLOW = Clonglong(1) << 31
const LWS_SERVER_OPTION_VH_H2_HALF_CLOSED_LONG_POLL = Clonglong(1) << 32
const LWS_SERVER_OPTION_GLIB = Clonglong(1) << 33
const LWS_SERVER_OPTION_H2_PRIOR_KNOWLEDGE = Clonglong(1) << 34
const LWS_SERVER_OPTION_NO_LWS_SYSTEM_STATES = Clonglong(1) << 35
const LWS_SERVER_OPTION_SS_PROXY = Clonglong(1) << 36
const LWS_SERVER_OPTION_SDEVENT = Clonglong(1) << 37
const LWS_SERVER_OPTION_ULOOP = Clonglong(1) << 38
const LWS_SERVER_OPTION_DISABLE_TLS_SESSION_CACHE = Clonglong(1) << 39

const LWS_RECOMMENDED_MIN_HEADER_SPACE = 2048
const LWS_H2_STREAM_SID = -1
const LWS_SEND_BUFFER_PRE_PADDING = LWS_PRE
const LWS_SEND_BUFFER_POST_PADDING = 0
const LWS_WRITE_RAW = LWS_WRITE_HTTP
const LWS_SESSION_TAG_LEN = 96
const LWS_CONTEXT_NULL = Ptr{Cvoid}(C_NULL)