WSI_INIT_TOKEN_MUXURL,
    WSI_PARSING_COMPLETE

export WSI_TOKEN_ACCEPT,
    WSI_TOKEN_CHALLENGE,
    WSI_TOKEN_COLON_PROTOCOL,
    WSI_TOKEN_CONNECT,
    WSI_TOKEN_CONNECTION,
    WSI_TOKEN_COUNT,
    WSI_TOKEN_DELETE_URI,
    WSI_TOKEN_DRAFT,
    WSI_TOKEN_DSS_SIGNATURE,
    WSI_TOKEN_EXTENSIONS,
    WSI_TOKEN_GET_URI,
    WSI_TOKEN_HEAD_URI,
    WSI_TOKEN_HOST,
    WSI_TOKEN_HTTP,
    WSI_TOKEN_HTTP1_0,
    WSI_TOKEN_HTTP2_SETTINGS,
    WSI_TOKEN_HTTP_ACCEPT,
    WSI_TOKEN_HTTP_ACCEPT_CHARSET,
    WSI_TOKEN_HTTP_ACCEPT_ENCODING,
    WSI_TOKEN_HTTP_ACCEPT_LANGUAGE,
    WSI_TOKEN_HTTP_ACCEPT_RANGES,
    WSI_TOKEN_HTTP_ACCESS_CONTROL_ALLOW_ORIGIN,
    WSI_TOKEN_HTTP_AC_REQUEST_HEADERS,
    WSI_TOKEN_HTTP_AGE,
    WSI_TOKEN_HTTP_ALLOW,
    WSI_TOKEN_HTTP_AUTHORIZATION,
    WSI_TOKEN_HTTP_CACHE_CONTROL,
    WSI_TOKEN_HTTP_COLON_AUTHORITY,
    WSI_TOKEN_HTTP_COLON_METHOD,
    WSI_TOKEN_HTTP_COLON_PATH,
    WSI_TOKEN_HTTP_COLON_SCHEME,
    WSI_TOKEN_HTTP_COLON_STATUS,
    WSI_TOKEN_HTTP_CONTENT_DISPOSITION,
    WSI_TOKEN_HTTP_CONTENT_ENCODING,
    WSI_TOKEN_HTTP_CONTENT_LANGUAGE,
    WSI_TOKEN_HTTP_CONTENT_LENGTH,
    WSI_TOKEN_HTTP_CONTENT_LOCATION,
    WSI_TOKEN_HTTP_CONTENT_RANGE,
    WSI_TOKEN_HTTP_CONTENT_TYPE,
    WSI_TOKEN_HTTP_COOKIE,
    WSI_TOKEN_HTTP_DATE,
    WSI_TOKEN_HTTP_ETAG,
    WSI_TOKEN_HTTP_EXPECT,
    WSI_TOKEN_HTTP_EXPIRES,
    WSI_TOKEN_HTTP_FROM,
    WSI_TOKEN_HTTP_IF_MATCH,
    WSI_TOKEN_HTTP_IF_MODIFIED_SINCE,
    WSI_TOKEN_HTTP_IF_NONE_MATCH,
    WSI_TOKEN_HTTP_IF_RANGE,
    WSI_TOKEN_HTTP_IF_UNMODIFIED_SINCE,
    WSI_TOKEN_HTTP_LAST_MODIFIED,
    WSI_TOKEN_HTTP_LINK,
    WSI_TOKEN_HTTP_LOCATION,
    WSI_TOKEN_HTTP_MAX_FORWARDS,
    WSI_TOKEN_HTTP_PRAGMA,
    WSI_TOKEN_HTTP_PROXY_AUTHENTICATE,
    WSI_TOKEN_HTTP_PROXY_AUTHORIZATION,
    WSI_TOKEN_HTTP_RANGE,
    WSI_TOKEN_HTTP_REFERER,
    WSI_TOKEN_HTTP_REFRESH,
    WSI_TOKEN_HTTP_RETRY_AFTER,
    WSI_TOKEN_HTTP_SERVER,
    WSI_TOKEN_HTTP_SET_COOKIE,
    WSI_TOKEN_HTTP_STRICT_TRANSPORT_SECURITY,
    WSI_TOKEN_HTTP_TRANSFER_ENCODING,
    WSI_TOKEN_HTTP_URI_ARGS,
    WSI_TOKEN_HTTP_USER_AGENT,
    WSI_TOKEN_HTTP_VARY,
    WSI_TOKEN_HTTP_VIA,
    WSI_TOKEN_HTTP_WWW_AUTHENTICATE,
    WSI_TOKEN_HTTP_X_REAL_IP,
    WSI_TOKEN_KEY,
    WSI_TOKEN_KEY1,
    WSI_TOKEN_KEY2,
    WSI_TOKEN_NAME_PART,
    WSI_TOKEN_NONCE,
    WSI_TOKEN_OPTIONS_URI,
    WSI_TOKEN_ORIGIN,
    WSI_TOKEN_PATCH_URI,
    WSI_TOKEN_POST_URI,
    WSI_TOKEN_PROTOCOL,
    WSI_TOKEN_PROXY,
    WSI_TOKEN_PUT_URI,
    WSI_TOKEN_REPLAY_NONCE,
    WSI_TOKEN_SKIPPING,
    WSI_TOKEN_SKIPPING_SAW_CR,
    WSI_TOKEN_SWORIGIN,
    WSI_TOKEN_TE,
    WSI_TOKEN_UNKNOWN_VALUE_PART,
    WSI_TOKEN_UPGRADE,
    WSI_TOKEN_VERSION,
    WSI_TOKEN_X_AUTH_TOKEN,
    WSI_TOKEN_X_FORWARDED_FOR

const WSI_TOKEN_GET_URI = 0 % UInt32
const WSI_TOKEN_POST_URI = 1 % UInt32
const WSI_TOKEN_OPTIONS_URI = 2 % UInt32
const WSI_TOKEN_HOST = 3 % UInt32
const WSI_TOKEN_CONNECTION = 4 % UInt32
const WSI_TOKEN_UPGRADE = 5 % UInt32
const WSI_TOKEN_ORIGIN = 6 % UInt32
const WSI_TOKEN_DRAFT = 7 % UInt32
const WSI_TOKEN_CHALLENGE = 8 % UInt32
const WSI_TOKEN_EXTENSIONS = 9 % UInt32
const WSI_TOKEN_KEY1 = 10 % UInt32
const WSI_TOKEN_KEY2 = 11 % UInt32
const WSI_TOKEN_PROTOCOL = 12 % UInt32
const WSI_TOKEN_ACCEPT = 13 % UInt32
const WSI_TOKEN_NONCE = 14 % UInt32
const WSI_TOKEN_HTTP = 15 % UInt32
const WSI_TOKEN_HTTP2_SETTINGS = 16 % UInt32
const WSI_TOKEN_HTTP_ACCEPT = 17 % UInt32
const WSI_TOKEN_HTTP_AC_REQUEST_HEADERS = 18 % UInt32
const WSI_TOKEN_HTTP_IF_MODIFIED_SINCE = 19 % UInt32
const WSI_TOKEN_HTTP_IF_NONE_MATCH = 20 % UInt32
const WSI_TOKEN_HTTP_ACCEPT_ENCODING = 21 % UInt32
const WSI_TOKEN_HTTP_ACCEPT_LANGUAGE = 22 % UInt32
const WSI_TOKEN_HTTP_PRAGMA = 23 % UInt32
const WSI_TOKEN_HTTP_CACHE_CONTROL = 24 % UInt32
const WSI_TOKEN_HTTP_AUTHORIZATION = 25 % UInt32
const WSI_TOKEN_HTTP_COOKIE = 26 % UInt32
const WSI_TOKEN_HTTP_CONTENT_LENGTH = 27 % UInt32
const WSI_TOKEN_HTTP_CONTENT_TYPE = 28 % UInt32
const WSI_TOKEN_HTTP_DATE = 29 % UInt32
const WSI_TOKEN_HTTP_RANGE = 30 % UInt32
const WSI_TOKEN_HTTP_REFERER = 31 % UInt32
const WSI_TOKEN_KEY = 32 % UInt32
const WSI_TOKEN_VERSION = 33 % UInt32
const WSI_TOKEN_SWORIGIN = 34 % UInt32
const WSI_TOKEN_HTTP_COLON_AUTHORITY = 35 % UInt32
const WSI_TOKEN_HTTP_COLON_METHOD = 36 % UInt32
const WSI_TOKEN_HTTP_COLON_PATH = 37 % UInt32
const WSI_TOKEN_HTTP_COLON_SCHEME = 38 % UInt32
const WSI_TOKEN_HTTP_COLON_STATUS = 39 % UInt32
const WSI_TOKEN_HTTP_ACCEPT_CHARSET = 40 % UInt32
const WSI_TOKEN_HTTP_ACCEPT_RANGES = 41 % UInt32
const WSI_TOKEN_HTTP_ACCESS_CONTROL_ALLOW_ORIGIN = 42 % UInt32
const WSI_TOKEN_HTTP_AGE = 43 % UInt32
const WSI_TOKEN_HTTP_ALLOW = 44 % UInt32
const WSI_TOKEN_HTTP_CONTENT_DISPOSITION = 45 % UInt32
const WSI_TOKEN_HTTP_CONTENT_ENCODING = 46 % UInt32
const WSI_TOKEN_HTTP_CONTENT_LANGUAGE = 47 % UInt32
const WSI_TOKEN_HTTP_CONTENT_LOCATION = 48 % UInt32
const WSI_TOKEN_HTTP_CONTENT_RANGE = 49 % UInt32
const WSI_TOKEN_HTTP_ETAG = 50 % UInt32
const WSI_TOKEN_HTTP_EXPECT = 51 % UInt32
const WSI_TOKEN_HTTP_EXPIRES = 52 % UInt32
const WSI_TOKEN_HTTP_FROM = 53 % UInt32
const WSI_TOKEN_HTTP_IF_MATCH = 54 % UInt32
const WSI_TOKEN_HTTP_IF_RANGE = 55 % UInt32
const WSI_TOKEN_HTTP_IF_UNMODIFIED_SINCE = 56 % UInt32
const WSI_TOKEN_HTTP_LAST_MODIFIED = 57 % UInt32
const WSI_TOKEN_HTTP_LINK = 58 % UInt32
const WSI_TOKEN_HTTP_LOCATION = 59 % UInt32
const WSI_TOKEN_HTTP_MAX_FORWARDS = 60 % UInt32
const WSI_TOKEN_HTTP_PROXY_AUTHENTICATE = 61 % UInt32
const WSI_TOKEN_HTTP_PROXY_AUTHORIZATION = 62 % UInt32
const WSI_TOKEN_HTTP_REFRESH = 63 % UInt32
const WSI_TOKEN_HTTP_RETRY_AFTER = 64 % UInt32
const WSI_TOKEN_HTTP_SERVER = 65 % UInt32
const WSI_TOKEN_HTTP_SET_COOKIE = 66 % UInt32
const WSI_TOKEN_HTTP_STRICT_TRANSPORT_SECURITY = 67 % UInt32
const WSI_TOKEN_HTTP_TRANSFER_ENCODING = 68 % UInt32
const WSI_TOKEN_HTTP_USER_AGENT = 69 % UInt32
const WSI_TOKEN_HTTP_VARY = 70 % UInt32
const WSI_TOKEN_HTTP_VIA = 71 % UInt32
const WSI_TOKEN_HTTP_WWW_AUTHENTICATE = 72 % UInt32
const WSI_TOKEN_PATCH_URI = 73 % UInt32
const WSI_TOKEN_PUT_URI = 74 % UInt32
const WSI_TOKEN_DELETE_URI = 75 % UInt32
const WSI_TOKEN_HTTP_URI_ARGS = 76 % UInt32
const WSI_TOKEN_PROXY = 77 % UInt32
const WSI_TOKEN_HTTP_X_REAL_IP = 78 % UInt32
const WSI_TOKEN_HTTP1_0 = 79 % UInt32
const WSI_TOKEN_X_FORWARDED_FOR = 80 % UInt32
const WSI_TOKEN_CONNECT = 81 % UInt32
const WSI_TOKEN_HEAD_URI = 82 % UInt32
const WSI_TOKEN_TE = 83 % UInt32
const WSI_TOKEN_REPLAY_NONCE = 84 % UInt32
const WSI_TOKEN_COLON_PROTOCOL = 85 % UInt32
const WSI_TOKEN_X_AUTH_TOKEN = 86 % UInt32
const WSI_TOKEN_DSS_SIGNATURE = 87 % UInt32
const _WSI_TOKEN_CLIENT_SENT_PROTOCOLS = 88 % UInt32
const _WSI_TOKEN_CLIENT_PEER_ADDRESS = 89 % UInt32
const _WSI_TOKEN_CLIENT_URI = 90 % UInt32
const _WSI_TOKEN_CLIENT_HOST = 91 % UInt32
const _WSI_TOKEN_CLIENT_ORIGIN = 92 % UInt32
const _WSI_TOKEN_CLIENT_METHOD = 93 % UInt32
const _WSI_TOKEN_CLIENT_IFACE = 94 % UInt32
const _WSI_TOKEN_CLIENT_ALPN = 95 % UInt32
const WSI_TOKEN_COUNT = 96 % UInt32
const WSI_TOKEN_NAME_PART = 97 % UInt32
const WSI_TOKEN_UNKNOWN_VALUE_PART = 98 % UInt32
const WSI_TOKEN_SKIPPING = 99 % UInt32
const WSI_TOKEN_SKIPPING_SAW_CR = 100 % UInt32
const WSI_PARSING_COMPLETE = 101 % UInt32
const WSI_INIT_TOKEN_MUXURL = 102 % UInt32